### ISSUE TITLE
How long will it take for building?

### ISSUE THREAD

**Issue by hduzq** [eth-sri/zapper#1]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/39996524/194712019-44107ccf-d1b5-4ddb-8666-b03cbe57ea4c.png">
What I do is I follow this page https://github.com/eth-sri/zapper
as the above image shows, it had taken more than 10k seconds.
May I know if it has something wrong?

**Comment by sam-steffen** [comment]
On my machine it does not take this long, potentially maturin is hanging. Can you try the following?
- Add the `--progress=plain --no-cache` flags to L40 in https://github.com/eth-sri/zapper/blob/main/docker/Makefile#L40 (this will enable printing the standard output of the RUN commands)
- Add the `--verbose` flag to L48 in https://github.com/eth-sri/zapper/blob/main/docker/Dockerfile#L48
- Try `make run` again and inspect the output

**Comment by hduzq** [comment]
Thanks for reply. I've processed pytest successfully,while maturin took about 16K seconds.I will try according your suggestion when next.
